### ISSUE TITLE
Container can't run, error: Node modules not installed 

### ISSUE THREAD

**Issue by AlexStack** [naskio/docker-strapi#8]
config:
```
strapi4:
    image: naskio/strapi:latest-alpine
    container_name: strapi4-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "9447:1337"
    environment:
      NODE_ENV: development
      DATABASE_HOST: mariadb
      DATABASE_CLIENT: mysql
      DATABASE_NAME: xxx
      DATABASE_USERNAME: xxx
      DATABASE_PASSWORD: xxx
      DATABASE_PORT: 3306
    # volumes:
    #   - ./docker_data/strapiapp:/srv/app
    networks:
      - default
```

error:
```

 Node modules not installed. Installing using npm ...
audited 1651 packages in 55.141s

118 packages are looking for funding
  run `npm fund` for details

found 106 vulnerabilities (3 low, 27 moderate, 59 high, 17 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Starting your app (with develop)...
You need to run strapi develop in a Strapi project. Make sure you are in the right directory.
Node modules not installed. Installing using npm ...
audited 1651 packages in 58.853s

118 packages are looking for funding
  run `npm fund` for details

found 106 vulnerabilities (3 low, 27 moderate, 59 high, 17 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Starting your app (with develop)...
You need to run strapi develop in a Strapi project. Make sure you are in the right directory.
Node modules not installed. Installing using npm ...
```

Tried set volumes, recreate, and all got the same error. any help?
